// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace HotelBooking.BddTests.Features.Bookings
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "ui")]
    [global::Xunit.TraitAttribute("Category", "current_behavior")]
    public partial class CreateBookingInTheCurrentMVCApplicationFeature : object, global::Xunit.IClassFixture<CreateBookingInTheCurrentMVCApplicationFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "ui",
                "current_behavior"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Bookings", "Create booking in the current MVC application", "  In order to document the delivered MVC behavior\r\n  As a tester\r\n  I want to cap" +
                "ture what the application does today, including defects", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Booking_CurrentMvcBehavior.feature"
#line hidden
        
        public CreateBookingInTheCurrentMVCApplicationFeature(CreateBookingInTheCurrentMVCApplicationFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
  #line hidden
#line 8
    await testRunner.GivenAsync("the booking form is open", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Bookings/Booking_CurrentMvcBehavior.feature.ndjson", 10);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="BB-01 Reject request when the start date is missing")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Create booking in the current MVC application")]
        [global::Xunit.TraitAttribute("Description", "BB-01 Reject request when the start date is missing")]
        [global::Xunit.TraitAttribute("Category", "bb01")]
        public async global::System.Threading.Tasks.Task BB_01RejectRequestWhenTheStartDateIsMissing()
        {
            string[] tagsOfScenario = new string[] {
                    "bb01"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BB-01 Reject request when the start date is missing", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Missing required dates are validated on the page", null, tagsOfRule);
#line 13
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 14
      await testRunner.WhenAsync("the user submits a booking without a start date and with end date \"2026-04-02\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
      await testRunner.ThenAsync("the booking is not created", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
      await testRunner.AndAsync("the user sees \"The StartDate field is required.\" below the start date field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="BB-02 Reject request when the end date is missing")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Create booking in the current MVC application")]
        [global::Xunit.TraitAttribute("Description", "BB-02 Reject request when the end date is missing")]
        [global::Xunit.TraitAttribute("Category", "bb02")]
        public async global::System.Threading.Tasks.Task BB_02RejectRequestWhenTheEndDateIsMissing()
        {
            string[] tagsOfScenario = new string[] {
                    "bb02"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BB-02 Reject request when the end date is missing", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Missing required dates are validated on the page", null, tagsOfRule);
#line 19
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 20
      await testRunner.WhenAsync("the user submits a booking with start date \"2026-04-01\" and without an end date", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
      await testRunner.ThenAsync("the booking is not created", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 22
      await testRunner.AndAsync("the user sees \"The EndDate field is required.\" below the end date field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="BB-03 Reject request when the start date is before today")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Create booking in the current MVC application")]
        [global::Xunit.TraitAttribute("Description", "BB-03 Reject request when the start date is before today")]
        [global::Xunit.TraitAttribute("Category", "known_bug")]
        [global::Xunit.TraitAttribute("Category", "bb03")]
        public async global::System.Threading.Tasks.Task BB_03RejectRequestWhenTheStartDateIsBeforeToday()
        {
            string[] tagsOfScenario = new string[] {
                    "known_bug",
                    "bb03"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BB-03 Reject request when the start date is before today", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Invalid date input currently causes an unhandled exception", null, tagsOfRule);
#line 27
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 28
      await testRunner.WhenAsync("the user submits a booking from a past date to a future date", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
      await testRunner.ThenAsync("the application crashes with an ArgumentException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 30
      await testRunner.AndAsync("the exception message is \"The start date cannot be in the past or later than the " +
                        "end date.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="BB-04 Reject request when the booking starts today")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Create booking in the current MVC application")]
        [global::Xunit.TraitAttribute("Description", "BB-04 Reject request when the booking starts today")]
        [global::Xunit.TraitAttribute("Category", "known_bug")]
        [global::Xunit.TraitAttribute("Category", "bb04")]
        public async global::System.Threading.Tasks.Task BB_04RejectRequestWhenTheBookingStartsToday()
        {
            string[] tagsOfScenario = new string[] {
                    "known_bug",
                    "bb04"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BB-04 Reject request when the booking starts today", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Invalid date input currently causes an unhandled exception", null, tagsOfRule);
#line 33
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 34
      await testRunner.WhenAsync("the user submits a booking that starts today and ends today", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
      await testRunner.ThenAsync("the application crashes with an ArgumentException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 36
      await testRunner.AndAsync("the exception message is \"The start date cannot be in the past or later than the " +
                        "end date.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="BB-06 Reject request when the start date is after the end date")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Create booking in the current MVC application")]
        [global::Xunit.TraitAttribute("Description", "BB-06 Reject request when the start date is after the end date")]
        [global::Xunit.TraitAttribute("Category", "known_bug")]
        [global::Xunit.TraitAttribute("Category", "bb06")]
        public async global::System.Threading.Tasks.Task BB_06RejectRequestWhenTheStartDateIsAfterTheEndDate()
        {
            string[] tagsOfScenario = new string[] {
                    "known_bug",
                    "bb06"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BB-06 Reject request when the start date is after the end date", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Invalid date input currently causes an unhandled exception", null, tagsOfRule);
#line 39
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 40
      await testRunner.WhenAsync("the user submits a booking with the start date after the end date", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
      await testRunner.ThenAsync("the application crashes with an ArgumentException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 42
      await testRunner.AndAsync("the exception message is \"The start date cannot be in the past or later than the " +
                        "end date.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="BB-05 Accept a future one-day booking when a room is available")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Create booking in the current MVC application")]
        [global::Xunit.TraitAttribute("Description", "BB-05 Accept a future one-day booking when a room is available")]
        [global::Xunit.TraitAttribute("Category", "bb05")]
        public async global::System.Threading.Tasks.Task BB_05AcceptAFutureOne_DayBookingWhenARoomIsAvailable()
        {
            string[] tagsOfScenario = new string[] {
                    "bb05"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BB-05 Accept a future one-day booking when a room is available", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Valid bookings are created when a room is available", null, tagsOfRule);
#line 47
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 48
      await testRunner.WhenAsync("the user submits a one-day booking outside the fully occupied period for customer" +
                        " \"John Smith\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
      await testRunner.ThenAsync("the user is redirected from \"/Bookings/Create\" to \"/Bookings\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 50
      await testRunner.AndAsync("the new booking appears in the bookings table", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="BB-07 Accept a future multi-day booking when a room is available")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Create booking in the current MVC application")]
        [global::Xunit.TraitAttribute("Description", "BB-07 Accept a future multi-day booking when a room is available")]
        [global::Xunit.TraitAttribute("Category", "bb07")]
        public async global::System.Threading.Tasks.Task BB_07AcceptAFutureMulti_DayBookingWhenARoomIsAvailable()
        {
            string[] tagsOfScenario = new string[] {
                    "bb07"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BB-07 Accept a future multi-day booking when a room is available", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Valid bookings are created when a room is available", null, tagsOfRule);
#line 53
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 54
      await testRunner.WhenAsync("the user submits a multi-day booking outside the fully occupied period for custom" +
                        "er \"Jane Doe\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
      await testRunner.ThenAsync("the user is redirected from \"/Bookings/Create\" to \"/Bookings\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 56
      await testRunner.AndAsync("the new booking appears in the bookings table", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="BB-08 Reject request when dates are valid but no room is available")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Create booking in the current MVC application")]
        [global::Xunit.TraitAttribute("Description", "BB-08 Reject request when dates are valid but no room is available")]
        [global::Xunit.TraitAttribute("Category", "bb08")]
        public async global::System.Threading.Tasks.Task BB_08RejectRequestWhenDatesAreValidButNoRoomIsAvailable()
        {
            string[] tagsOfScenario = new string[] {
                    "bb08"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BB-08 Reject request when dates are valid but no room is available", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Valid dates with no availability show an on-page status message", null, tagsOfRule);
#line 61
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 62
      await testRunner.WhenAsync("the user submits a booking inside the fully occupied period for customer \"John Sm" +
                        "ith\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
      await testRunner.ThenAsync("the booking is not created", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 64
      await testRunner.AndAsync("the user stays on \"/Bookings/Create\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
      await testRunner.AndAsync("the user sees \"The booking could not be created. There were no available room.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CreateBookingInTheCurrentMVCApplicationFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CreateBookingInTheCurrentMVCApplicationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
