// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace HotelBooking.CucumberTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class FullyOccupiedDatesFeature : object, global::Xunit.IClassFixture<FullyOccupiedDatesFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Fully Occupied Dates", "  As a hotel manager\r\n  I want to see which dates are fully occupied\r\n  So that I" +
                " can inform customers about availability", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "FullyOccupiedDates.feature"
#line hidden
        
        public FullyOccupiedDatesFeature(FullyOccupiedDatesFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("the hotel has 3 rooms", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("room 1 is booked from \"today+10\" to \"today+20\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.AndAsync("room 2 is booked from \"today+10\" to \"today+20\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
    await testRunner.AndAsync("room 3 is booked from \"today+10\" to \"today+20\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/FullyOccupiedDates.feature", @"Feature: Fully Occupied Dates
  As a hotel manager
  I want to see which dates are fully occupied
  So that I can inform customers about availability

  Background:
    Given the hotel has 3 rooms
    And room 1 is booked from ""today+10"" to ""today+20""
    And room 2 is booked from ""today+10"" to ""today+20""
    And room 3 is booked from ""today+10"" to ""today+20""

  Scenario: All dates in the occupied period are returned as fully occupied
    When I request fully occupied dates from ""today+10"" to ""today+20""
    Then 11 fully occupied dates should be returned
    And all dates from ""today+10"" to ""today+20"" should be in the result

  Scenario: No fully occupied dates outside the booked period
    When I request fully occupied dates from ""today+1"" to ""today+9""
    Then 0 fully occupied dates should be returned

  Scenario: Partially overlapping query returns only occupied dates
    When I request fully occupied dates from ""today+8"" to ""today+12""
    Then 3 fully occupied dates should be returned
    And all dates from ""today+10"" to ""today+12"" should be in the result

  Scenario: Invalid date range throws exception
    When I request fully occupied dates from ""today+20"" to ""today+10""
    Then an ArgumentException should be thrown for fully occupied dates

", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/FullyOccupiedDates.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Fully Occupied Dates", "  As a hotel manager\r\n  I want to see which dates are fully occupied\r\n  So that I" +
                        " can inform customers about availability", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the hotel has 3 rooms", null, null, "1671ccca4b403c53a7cd7759bf38745a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "room 1 is booked from \"today+10\" to \"today+20\"", null, null, "c1026545a51d1f52b8a0d524cb45704e"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "room 2 is booked from \"today+10\" to \"today+20\"", null, null, "a8b5e9fcefb03b53afa7a31df4821fc7"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "room 3 is booked from \"today+10\" to \"today+20\"", null, null, "50ef380c947c7453825fe4b09dd7d79b")}), "1ca57d25302a7a5ab1b92e118ec71d00"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "All dates in the occupied period are returned as fully occupied", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I request fully occupied dates from \"today+10\" to \"today+20\"", null, null, "f6884209d28d3253b1ab532f891efd66"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "11 fully occupied dates should be returned", null, null, "bac4b334f43831518637179f1550902e"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "all dates from \"today+10\" to \"today+20\" should be in the result", null, null, "79316a2e04c80c52b0fa6fcfa211bad8")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "1ac4ddf2d9ebbd52abb0fbddcdf9143c")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "No fully occupied dates outside the booked period", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I request fully occupied dates from \"today+1\" to \"today+9\"", null, null, "098b9e18a13d8350a5a14498339f20f4"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "0 fully occupied dates should be returned", null, null, "30d2a4b88a28865585f1736e7c1831cf")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "0a6841eec632c458b61cbe5d1fd24ac6")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Partially overlapping query returns only occupied dates", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I request fully occupied dates from \"today+8\" to \"today+12\"", null, null, "afd75974f14c1f56ae61db1b3970b5f9"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "3 fully occupied dates should be returned", null, null, "75cd11aace0e4857a054526bde48f134"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "all dates from \"today+10\" to \"today+12\" should be in the result", null, null, "c9af7623b6790b52a299a35d0a771143")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "98d813e8f68c6a5b905de1a57df59201")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Invalid date range throws exception", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I request fully occupied dates from \"today+20\" to \"today+10\"", null, null, "5033ffa8e68311528c63b14e80701dc9"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "an ArgumentException should be thrown for fully occupied dates", null, null, "67b23a377c7e7a55a21a4ff658d30b02")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "673a1e33f1ecae54ae3ad4638c3404be"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("c3c1ed9ae3a118519c64b08be59744d3", "Features/FullyOccupiedDates.feature", "All dates in the occupied period are returned as fully occupied", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1671ccca4b403c53a7cd7759bf38745a"}), "587600adbb087950aebca36ab6dd6c5a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the hotel has 3 rooms"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c1026545a51d1f52b8a0d524cb45704e"}), "ea7b65c7b590dc59952c7ba6ef11044a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "room 1 is booked from \"today+10\" to \"today+20\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a8b5e9fcefb03b53afa7a31df4821fc7"}), "40c2c98756ac3b5588bcf4a1b0612fd2", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "room 2 is booked from \"today+10\" to \"today+20\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "50ef380c947c7453825fe4b09dd7d79b"}), "d63d16df33872850a833a7757e45810c", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "room 3 is booked from \"today+10\" to \"today+20\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f6884209d28d3253b1ab532f891efd66"}), "9e3fa4c68ee9b15bb335829146a60360", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I request fully occupied dates from \"today+10\" to \"today+20\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "bac4b334f43831518637179f1550902e"}), "a25735a57182e056b03c77604a940684", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "11 fully occupied dates should be returned"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "79316a2e04c80c52b0fa6fcfa211bad8"}), "0bf00827370c5c5d8811671185698699", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "all dates from \"today+10\" to \"today+20\" should be in the result")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "1ac4ddf2d9ebbd52abb0fbddcdf9143c"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("45307dae22b1d452adbd45b4391e6740", "Features/FullyOccupiedDates.feature", "No fully occupied dates outside the booked period", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1671ccca4b403c53a7cd7759bf38745a"}), "76a2cda38eaf465f81e9fbd7b924fc04", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the hotel has 3 rooms"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c1026545a51d1f52b8a0d524cb45704e"}), "e746352dfe06f851a2d4594ff10f1450", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "room 1 is booked from \"today+10\" to \"today+20\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a8b5e9fcefb03b53afa7a31df4821fc7"}), "28d2207d1d299858b97a8931791be595", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "room 2 is booked from \"today+10\" to \"today+20\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "50ef380c947c7453825fe4b09dd7d79b"}), "194c8a197ab52c54856e49f2889ed95b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "room 3 is booked from \"today+10\" to \"today+20\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "098b9e18a13d8350a5a14498339f20f4"}), "d8b71fe101be555a813af5b6e0e67220", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I request fully occupied dates from \"today+1\" to \"today+9\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "30d2a4b88a28865585f1736e7c1831cf"}), "7b38defa63947c5dabad98a2771fef79", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "0 fully occupied dates should be returned")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "0a6841eec632c458b61cbe5d1fd24ac6"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("1107a86d6342a3529329e15e40201028", "Features/FullyOccupiedDates.feature", "Partially overlapping query returns only occupied dates", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1671ccca4b403c53a7cd7759bf38745a"}), "46d04bd79a3801519bb68c55639bb31e", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the hotel has 3 rooms"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c1026545a51d1f52b8a0d524cb45704e"}), "68aa81056de1cd5aaf33c3a4e689ab39", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "room 1 is booked from \"today+10\" to \"today+20\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a8b5e9fcefb03b53afa7a31df4821fc7"}), "e1d42cfe01730d5a9eacb22d7e718bb9", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "room 2 is booked from \"today+10\" to \"today+20\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "50ef380c947c7453825fe4b09dd7d79b"}), "99336fbfe7c8bd5c8be89f3dd2f942d6", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "room 3 is booked from \"today+10\" to \"today+20\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "afd75974f14c1f56ae61db1b3970b5f9"}), "fb757af05143b251bf8091a36521a9eb", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I request fully occupied dates from \"today+8\" to \"today+12\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "75cd11aace0e4857a054526bde48f134"}), "2e27183428a47053823bdb5f8925aa0b", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "3 fully occupied dates should be returned"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c9af7623b6790b52a299a35d0a771143"}), "45bb671e27a1265cb8ae00d736638101", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "all dates from \"today+10\" to \"today+12\" should be in the result")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "98d813e8f68c6a5b905de1a57df59201"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("066fe9cedc741f5daa1fd820c6407dc5", "Features/FullyOccupiedDates.feature", "Invalid date range throws exception", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1671ccca4b403c53a7cd7759bf38745a"}), "360f55701b11c851868b1ab9f17d9dac", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the hotel has 3 rooms"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c1026545a51d1f52b8a0d524cb45704e"}), "93f79da0b28aa2588532ec6df7e28c89", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "room 1 is booked from \"today+10\" to \"today+20\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a8b5e9fcefb03b53afa7a31df4821fc7"}), "6721999021bbdc5f9fd676b81f3d86c7", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "room 2 is booked from \"today+10\" to \"today+20\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "50ef380c947c7453825fe4b09dd7d79b"}), "99502b106bab895daa8c914d92b359ac", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "room 3 is booked from \"today+10\" to \"today+20\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5033ffa8e68311528c63b14e80701dc9"}), "74c3be4ecf1b0e50992c8e2e56e48e2e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I request fully occupied dates from \"today+20\" to \"today+10\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "67b23a377c7e7a55a21a4ff658d30b02"}), "3021d40900571051838123ab4c925a5b", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "an ArgumentException should be thrown for fully occupied dates")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "673a1e33f1ecae54ae3ad4638c3404be"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(FullyOccupiedDatesFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(FullyOccupiedDatesFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(FullyOccupiedDatesFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="All dates in the occupied period are returned as fully occupied")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Fully Occupied Dates")]
        [global::Xunit.TraitAttribute("Description", "All dates in the occupied period are returned as fully occupied")]
        public async global::System.Threading.Tasks.Task AllDatesInTheOccupiedPeriodAreReturnedAsFullyOccupied()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("All dates in the occupied period are returned as fully occupied", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 13
    await testRunner.WhenAsync("I request fully occupied dates from \"today+10\" to \"today+20\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
    await testRunner.ThenAsync("11 fully occupied dates should be returned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 15
    await testRunner.AndAsync("all dates from \"today+10\" to \"today+20\" should be in the result", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="No fully occupied dates outside the booked period")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Fully Occupied Dates")]
        [global::Xunit.TraitAttribute("Description", "No fully occupied dates outside the booked period")]
        public async global::System.Threading.Tasks.Task NoFullyOccupiedDatesOutsideTheBookedPeriod()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No fully occupied dates outside the booked period", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 18
    await testRunner.WhenAsync("I request fully occupied dates from \"today+1\" to \"today+9\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
    await testRunner.ThenAsync("0 fully occupied dates should be returned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Partially overlapping query returns only occupied dates")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Fully Occupied Dates")]
        [global::Xunit.TraitAttribute("Description", "Partially overlapping query returns only occupied dates")]
        public async global::System.Threading.Tasks.Task PartiallyOverlappingQueryReturnsOnlyOccupiedDates()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Partially overlapping query returns only occupied dates", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 21
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 22
    await testRunner.WhenAsync("I request fully occupied dates from \"today+8\" to \"today+12\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
    await testRunner.ThenAsync("3 fully occupied dates should be returned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 24
    await testRunner.AndAsync("all dates from \"today+10\" to \"today+12\" should be in the result", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Invalid date range throws exception")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Fully Occupied Dates")]
        [global::Xunit.TraitAttribute("Description", "Invalid date range throws exception")]
        public async global::System.Threading.Tasks.Task InvalidDateRangeThrowsException()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Invalid date range throws exception", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 26
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 27
    await testRunner.WhenAsync("I request fully occupied dates from \"today+20\" to \"today+10\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
    await testRunner.ThenAsync("an ArgumentException should be thrown for fully occupied dates", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await FullyOccupiedDatesFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await FullyOccupiedDatesFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
